Header header


# Total Received Bytes over interface, NOTE int64
int64 rx_bytes_total

# Total Transmitted Bytes over interface,  NOTE int64
int64 tx_bytes_total


# Total Received Bytes over interface since last 
float32 rx_megabits_use

# Total Transmitted Bytes over interface since last 
float32 tx_megabits_use


# UDP Received Bytes over interface
int32 rx_bytes_udp

# UDP Transmitted Bytes over interface
int32 tx_bytes_udp



# TCP Received Bytes over interface
int32 rx_bytes_tcp

# TCP Transmitted Bytes over interface
int32 tx_bytes_tcp