Header header

string type

# LTE fields
string mode
string scell_id
string pcell_id
string EARFCN
int32 band_id

int8 LTE_ULBW
int8 LTE_DLBW
string LTE_TAC
int16 LTE_RSRQ
int16 LTE_RSRP
int16 LTE_RSSI
int16 LTE_SINR
int16 tx_power
int16 srxlec

int8 LTE_MCS
int8 LTE_RI
int8 LTE_CQI
int16 LTE_PMI


# NSA fields
string MNC
int32 NR_PCID
string NR_ARFCN
int16 NR_RSRP
int16 NR_RSRQ
int16 NR_SINR
int16 NR_BAND
int8 NR_BANDWIDTH
int16 NR_SCS

int8 NR_MCS
int8 NR_RI
int8 NR_CQI
int16 NR_PMI
string message