Header header

string type

# LTE fields
string mode
string scell_id
string pcell_id
string EARFCN
int32 band_id
int32 ULBW
int32 DLBW
string TAC
int32 RSRQ
int32 RSRP
int32 RSSI
int32 SINR
int32 CQI
int32 tx_power
int32 srxlec

# NSA fields
# Use the same fields as LTE where applicable and add any NSA-specific fields

int32 NR_PCID
string NR_ARFCN
int32 NR_RSRP
int32 NR_RSRQ
int32 NR_SINR
int32 NR_BAND
int32 NR_BANDWIDTH
int32 NR_SCS