Header header

# type of cellular connection (lte, SA, NSA)
string type


#operation mode                             Online
string operation_mode                       


#Physical Cell ID                           644
int64 pcell_id


#Frequency band                             NR5G_BAND78
string band


#E-Utra Abs Radio Freq Channel Number       627264
string earfcn       


# Reference Signal Received Power           -960
float32 rsrp 

# Reference Signal Received Quality         -120
float32 rsrq


# Signal to noise ratio                      95
int32 snr