Header header

# type of cellular connection (lte, ..)
string type


#operation mode                             Online
string operation_mode                       


#Tracking Area Code                         0x765D
string tac 

#Service Cell ID                            4955280
int64 scell_id

#Physical Cell ID                           0 
int64 pcell_id


#Frequency band                             NR5G_BAND78
string band


#E-Utra Abs Radio Freq Channel Number       640704
string earfcn       


# Reference Signal Received Power           -740
float32 rsrp 

# Reference Signal Received Quality         -110
float32 rsrq


# Signal to noise ratio                     240
int32 snr